Traceback (most recent call last):
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# prep year 
# convert to 
ca_temps.date_year = ca_temps.date_year.str.slice(0,4)

ca_temps.date_year = ca_temps.date_year.astype(int)

ca_temps.set_index('date_year', inplace=True)

ca_temps.tail()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn [38], line 5[0m
[0;32m      1[0m [38;5;66;03m# prep year [39;00m
[0;32m      2[0m [38;5;66;03m# convert to [39;00m
[0;32m      3[0m ca_temps[38;5;241m.[39mdate_year [38;5;241m=[39m ca_temps[38;5;241m.[39mdate_year[38;5;241m.[39mstr[38;5;241m.[39mslice([38;5;241m0[39m,[38;5;241m4[39m)
[1;32m----> 5[0m ca_temps[38;5;241m.[39mdate_year [38;5;241m=[39m [43mca_temps[49m[38;5;241;43m.[39;49m[43mdate_year[49m[38;5;241;43m.[39;49m[43mastype[49m[43m([49m[38;5;28;43mint[39;49m[43m)[49m
[0;32m      7[0m ca_temps[38;5;241m.[39mset_index([38;5;124m'[39m[38;5;124mdate_year[39m[38;5;124m'[39m, inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      9[0m ca_temps[38;5;241m.[39mtail()

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\generic.py:5912[0m, in [0;36mNDFrame.astype[1;34m(self, dtype, copy, errors)[0m
[0;32m   5905[0m     results [38;5;241m=[39m [
[0;32m   5906[0m         [38;5;28mself[39m[38;5;241m.[39miloc[:, i][38;5;241m.[39mastype(dtype, copy[38;5;241m=[39mcopy)
[0;32m   5907[0m         [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mcolumns))
[0;32m   5908[0m     ]
[0;32m   5910[0m [38;5;28;01melse[39;00m:
[0;32m   5911[0m     [38;5;66;03m# else, only a single dtype is given[39;00m
[1;32m-> 5912[0m     new_data [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_mgr[49m[38;5;241;43m.[39;49m[43mastype[49m[43m([49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m,[49m[43m [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m)[49m
[0;32m   5913[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_constructor(new_data)[38;5;241m.[39m__finalize__([38;5;28mself[39m, method[38;5;241m=[39m[38;5;124m"[39m[38;5;124mastype[39m[38;5;124m"[39m)
[0;32m   5915[0m [38;5;66;03m# GH 33113: handle empty frame or series[39;00m

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\internals\managers.py:419[0m, in [0;36mBaseBlockManager.astype[1;34m(self, dtype, copy, errors)[0m
[0;32m    418[0m [38;5;28;01mdef[39;00m [38;5;21mastype[39m([38;5;28mself[39m: T, dtype, copy: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m, errors: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m) [38;5;241m-[39m[38;5;241m>[39m T:
[1;32m--> 419[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mapply[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mastype[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m,[49m[43m [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m)[49m

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\internals\managers.py:304[0m, in [0;36mBaseBlockManager.apply[1;34m(self, f, align_keys, ignore_failures, **kwargs)[0m
[0;32m    302[0m         applied [38;5;241m=[39m b[38;5;241m.[39mapply(f, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    303[0m     [38;5;28;01melse[39;00m:
[1;32m--> 304[0m         applied [38;5;241m=[39m [38;5;28mgetattr[39m(b, f)([38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    305[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mTypeError[39;00m, [38;5;167;01mNotImplementedError[39;00m):
[0;32m    306[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ignore_failures:

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\internals\blocks.py:580[0m, in [0;36mBlock.astype[1;34m(self, dtype, copy, errors)[0m
[0;32m    562[0m [38;5;124;03m"""[39;00m
[0;32m    563[0m [38;5;124;03mCoerce to the new dtype.[39;00m
[0;32m    564[0m 
[1;32m   (...)[0m
[0;32m    576[0m [38;5;124;03mBlock[39;00m
[0;32m    577[0m [38;5;124;03m"""[39;00m
[0;32m    578[0m values [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mvalues
[1;32m--> 580[0m new_values [38;5;241m=[39m [43mastype_array_safe[49m[43m([49m[43mvalues[49m[43m,[49m[43m [49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m,[49m[43m [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m)[49m
[0;32m    582[0m new_values [38;5;241m=[39m maybe_coerce_values(new_values)
[0;32m    583[0m newb [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mmake_block(new_values)

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\dtypes\cast.py:1292[0m, in [0;36mastype_array_safe[1;34m(values, dtype, copy, errors)[0m
[0;32m   1289[0m     dtype [38;5;241m=[39m dtype[38;5;241m.[39mnumpy_dtype
[0;32m   1291[0m [38;5;28;01mtry[39;00m:
[1;32m-> 1292[0m     new_values [38;5;241m=[39m [43mastype_array[49m[43m([49m[43mvalues[49m[43m,[49m[43m [49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m)[49m
[0;32m   1293[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mValueError[39;00m, [38;5;167;01mTypeError[39;00m):
[0;32m   1294[0m     [38;5;66;03m# e.g. astype_nansafe can fail on object-dtype of strings[39;00m
[0;32m   1295[0m     [38;5;66;03m#  trying to convert to float[39;00m
[0;32m   1296[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m:

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\dtypes\cast.py:1237[0m, in [0;36mastype_array[1;34m(values, dtype, copy)[0m
[0;32m   1234[0m     values [38;5;241m=[39m values[38;5;241m.[39mastype(dtype, copy[38;5;241m=[39mcopy)
[0;32m   1236[0m [38;5;28;01melse[39;00m:
[1;32m-> 1237[0m     values [38;5;241m=[39m [43mastype_nansafe[49m[43m([49m[43mvalues[49m[43m,[49m[43m [49m[43mdtype[49m[43m,[49m[43m [49m[43mcopy[49m[38;5;241;43m=[39;49m[43mcopy[49m[43m)[49m
[0;32m   1239[0m [38;5;66;03m# in pandas we don't store numpy str dtypes, so convert to object[39;00m
[0;32m   1240[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(dtype, np[38;5;241m.[39mdtype) [38;5;129;01mand[39;00m [38;5;28missubclass[39m(values[38;5;241m.[39mdtype[38;5;241m.[39mtype, [38;5;28mstr[39m):

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\core\dtypes\cast.py:1154[0m, in [0;36mastype_nansafe[1;34m(arr, dtype, copy, skipna)[0m
[0;32m   1150[0m [38;5;28;01melif[39;00m is_object_dtype(arr[38;5;241m.[39mdtype):
[0;32m   1151[0m 
[0;32m   1152[0m     [38;5;66;03m# work around NumPy brokenness, #1987[39;00m
[0;32m   1153[0m     [38;5;28;01mif[39;00m np[38;5;241m.[39missubdtype(dtype[38;5;241m.[39mtype, np[38;5;241m.[39minteger):
[1;32m-> 1154[0m         [38;5;28;01mreturn[39;00m [43mlib[49m[38;5;241;43m.[39;49m[43mastype_intsafe[49m[43m([49m[43marr[49m[43m,[49m[43m [49m[43mdtype[49m[43m)[49m
[0;32m   1156[0m     [38;5;66;03m# if we have a datetime/timedelta array of objects[39;00m
[0;32m   1157[0m     [38;5;66;03m# then coerce to a proper dtype and recall astype_nansafe[39;00m
[0;32m   1159[0m     [38;5;28;01melif[39;00m is_datetime64_dtype(dtype):

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\pandas\_libs\lib.pyx:668[0m, in [0;36mpandas._libs.lib.astype_intsafe[1;34m()[0m

[1;31mValueError[0m: cannot convert float NaN to integer
ValueError: cannot convert float NaN to integer

