Traceback (most recent call last):
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# QQPLOT 
import pingouin as pg
ax = pg.qqplot(penguins.flipper_length_mm, dist='norm')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [6], line 2[0m
[0;32m      1[0m [38;5;66;03m# QQPLOT [39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpingouin[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpg[39;00m
[0;32m      3[0m ax [38;5;241m=[39m pg[38;5;241m.[39mqqplot(penguins[38;5;241m.[39mflipper_length_mm, dist[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnorm[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pingouin'
ModuleNotFoundError: No module named 'pingouin'

