Traceback (most recent call last):
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import seaborn as sns
import pandas as pd

dff = pd.DataFrame(list_of_data)
dff = dff.T#.to_numpy().flatten()

fig, ax=plt.subplots(1,2, figsize=(12,4))

dff.plot(kind='hist', color='b', alpha=.1, ax=ax[0], legend=False);
sns.histplot(list_of_means,ax=ax[1]);
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn [4], line 10[0m
[0;32m      7[0m fig, ax[38;5;241m=[39mplt[38;5;241m.[39msubplots([38;5;241m1[39m,[38;5;241m2[39m, figsize[38;5;241m=[39m([38;5;241m12[39m,[38;5;241m4[39m))
[0;32m      9[0m dff[38;5;241m.[39mplot(kind[38;5;241m=[39m[38;5;124m'[39m[38;5;124mhist[39m[38;5;124m'[39m, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mb[39m[38;5;124m'[39m, alpha[38;5;241m=[39m[38;5;241m.1[39m, ax[38;5;241m=[39max[[38;5;241m0[39m], legend[38;5;241m=[39m[38;5;28;01mFalse[39;00m);
[1;32m---> 10[0m sns[38;5;241m.[39mhistplot(list_of_means,ax[38;5;241m=[39max[[38;5;241m1[39m])

[1;31mAttributeError[0m: module 'seaborn' has no attribute 'histplot'
AttributeError: module 'seaborn' has no attribute 'histplot'

