Traceback (most recent call last):
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fires = gpd.read_file('https://github.com/barguzin/geo_data/raw/main/fires.zip')
print(fires.shape) 
print(type(fires))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mRemoteDisconnected[0m                        Traceback (most recent call last)
Cell [1;32mIn [3], line 1[0m
[1;32m----> 1[0m fires [38;5;241m=[39m [43mgpd[49m[38;5;241;43m.[39;49m[43mread_file[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mhttps://github.com/barguzin/geo_data/raw/main/fires.zip[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m [38;5;28mprint[39m(fires[38;5;241m.[39mshape) 
[0;32m      3[0m [38;5;28mprint[39m([38;5;28mtype[39m(fires))

File [1;32m~\anaconda3\envs\geo_env\lib\site-packages\geopandas\io\file.py:242[0m, in [0;36m_read_file[1;34m(filename, bbox, mask, rows, engine, **kwargs)[0m
[0;32m    240[0m from_bytes [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m    241[0m [38;5;28;01mif[39;00m _is_url(filename):
[1;32m--> 242[0m     req [38;5;241m=[39m [43m_urlopen[49m[43m([49m[43mfilename[49m[43m)[49m
[0;32m    243[0m     path_or_bytes [38;5;241m=[39m req[38;5;241m.[39mread()
[0;32m    244[0m     from_bytes [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:216[0m, in [0;36murlopen[1;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[0;32m    214[0m [38;5;28;01melse[39;00m:
[0;32m    215[0m     opener [38;5;241m=[39m _opener
[1;32m--> 216[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:525[0m, in [0;36mOpenerDirector.open[1;34m(self, fullurl, data, timeout)[0m
[0;32m    523[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[0;32m    524[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[1;32m--> 525[0m     response [38;5;241m=[39m [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[0;32m    527[0m [38;5;28;01mreturn[39;00m response

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:634[0m, in [0;36mHTTPErrorProcessor.http_response[1;34m(self, request, response)[0m
[0;32m    631[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[0;32m    632[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[0;32m    633[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[1;32m--> 634[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43merror[49m[43m([49m
[0;32m    635[0m [43m        [49m[38;5;124;43m'[39;49m[38;5;124;43mhttp[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[0;32m    637[0m [38;5;28;01mreturn[39;00m response

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:557[0m, in [0;36mOpenerDirector.error[1;34m(self, proto, *args)[0m
[0;32m    555[0m     http_err [38;5;241m=[39m [38;5;241m0[39m
[0;32m    556[0m args [38;5;241m=[39m ([38;5;28mdict[39m, proto, meth_name) [38;5;241m+[39m args
[1;32m--> 557[0m result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[0;32m    558[0m [38;5;28;01mif[39;00m result:
[0;32m    559[0m     [38;5;28;01mreturn[39;00m result

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:496[0m, in [0;36mOpenerDirector._call_chain[1;34m(self, chain, kind, meth_name, *args)[0m
[0;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[0;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[1;32m--> 496[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[0;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:749[0m, in [0;36mHTTPRedirectHandler.http_error_302[1;34m(self, req, fp, code, msg, headers)[0m
[0;32m    746[0m fp[38;5;241m.[39mread()
[0;32m    747[0m fp[38;5;241m.[39mclose()
[1;32m--> 749[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mnew[49m[43m,[49m[43m [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mreq[49m[38;5;241;43m.[39;49m[43mtimeout[49m[43m)[49m

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:519[0m, in [0;36mOpenerDirector.open[1;34m(self, fullurl, data, timeout)[0m
[0;32m    516[0m     req [38;5;241m=[39m meth(req)
[0;32m    518[0m sys[38;5;241m.[39maudit([38;5;124m'[39m[38;5;124murllib.Request[39m[38;5;124m'[39m, req[38;5;241m.[39mfull_url, req[38;5;241m.[39mdata, req[38;5;241m.[39mheaders, req[38;5;241m.[39mget_method())
[1;32m--> 519[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[0;32m    521[0m [38;5;66;03m# post-process response[39;00m
[0;32m    522[0m meth_name [38;5;241m=[39m protocol[38;5;241m+[39m[38;5;124m"[39m[38;5;124m_response[39m[38;5;124m"[39m

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:536[0m, in [0;36mOpenerDirector._open[1;34m(self, req, data)[0m
[0;32m    533[0m     [38;5;28;01mreturn[39;00m result
[0;32m    535[0m protocol [38;5;241m=[39m req[38;5;241m.[39mtype
[1;32m--> 536[0m result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhandle_open[49m[43m,[49m[43m [49m[43mprotocol[49m[43m,[49m[43m [49m[43mprotocol[49m[43m [49m[38;5;241;43m+[39;49m
[0;32m    537[0m [43m                          [49m[38;5;124;43m'[39;49m[38;5;124;43m_open[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mreq[49m[43m)[49m
[0;32m    538[0m [38;5;28;01mif[39;00m result:
[0;32m    539[0m     [38;5;28;01mreturn[39;00m result

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:496[0m, in [0;36mOpenerDirector._call_chain[1;34m(self, chain, kind, meth_name, *args)[0m
[0;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[0;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[1;32m--> 496[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[0;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:1391[0m, in [0;36mHTTPSHandler.https_open[1;34m(self, req)[0m
[0;32m   1390[0m [38;5;28;01mdef[39;00m [38;5;21mhttps_open[39m([38;5;28mself[39m, req):
[1;32m-> 1391[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdo_open[49m[43m([49m[43mhttp[49m[38;5;241;43m.[39;49m[43mclient[49m[38;5;241;43m.[39;49m[43mHTTPSConnection[49m[43m,[49m[43m [49m[43mreq[49m[43m,[49m
[0;32m   1392[0m [43m        [49m[43mcontext[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_context[49m[43m,[49m[43m [49m[43mcheck_hostname[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_hostname[49m[43m)[49m

File [1;32m~\anaconda3\envs\geo_env\lib\urllib\request.py:1352[0m, in [0;36mAbstractHTTPHandler.do_open[1;34m(self, http_class, req, **http_conn_args)[0m
[0;32m   1350[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m
[0;32m   1351[0m         [38;5;28;01mraise[39;00m URLError(err)
[1;32m-> 1352[0m     r [38;5;241m=[39m [43mh[49m[38;5;241;43m.[39;49m[43mgetresponse[49m[43m([49m[43m)[49m
[0;32m   1353[0m [38;5;28;01mexcept[39;00m:
[0;32m   1354[0m     h[38;5;241m.[39mclose()

File [1;32m~\anaconda3\envs\geo_env\lib\http\client.py:1374[0m, in [0;36mHTTPConnection.getresponse[1;34m(self)[0m
[0;32m   1372[0m [38;5;28;01mtry[39;00m:
[0;32m   1373[0m     [38;5;28;01mtry[39;00m:
[1;32m-> 1374[0m         [43mresponse[49m[38;5;241;43m.[39;49m[43mbegin[49m[43m([49m[43m)[49m
[0;32m   1375[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mConnectionError[39;00m:
[0;32m   1376[0m         [38;5;28mself[39m[38;5;241m.[39mclose()

File [1;32m~\anaconda3\envs\geo_env\lib\http\client.py:318[0m, in [0;36mHTTPResponse.begin[1;34m(self)[0m
[0;32m    316[0m [38;5;66;03m# read until we get a non-100 response[39;00m
[0;32m    317[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[1;32m--> 318[0m     version, status, reason [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_status[49m[43m([49m[43m)[49m
[0;32m    319[0m     [38;5;28;01mif[39;00m status [38;5;241m!=[39m CONTINUE:
[0;32m    320[0m         [38;5;28;01mbreak[39;00m

File [1;32m~\anaconda3\envs\geo_env\lib\http\client.py:287[0m, in [0;36mHTTPResponse._read_status[1;34m(self)[0m
[0;32m    283[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mreply:[39m[38;5;124m"[39m, [38;5;28mrepr[39m(line))
[0;32m    284[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m line:
[0;32m    285[0m     [38;5;66;03m# Presumably, the server closed the connection before[39;00m
[0;32m    286[0m     [38;5;66;03m# sending a valid response.[39;00m
[1;32m--> 287[0m     [38;5;28;01mraise[39;00m RemoteDisconnected([38;5;124m"[39m[38;5;124mRemote end closed connection without[39m[38;5;124m"[39m
[0;32m    288[0m                              [38;5;124m"[39m[38;5;124m response[39m[38;5;124m"[39m)
[0;32m    289[0m [38;5;28;01mtry[39;00m:
[0;32m    290[0m     version, status, reason [38;5;241m=[39m line[38;5;241m.[39msplit([38;5;28;01mNone[39;00m, [38;5;241m2[39m)

[1;31mRemoteDisconnected[0m: Remote end closed connection without response
RemoteDisconnected: Remote end closed connection without response

