Traceback (most recent call last):
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Generate scatter plot
f, ax = plt.subplots()

sns.histplot(x="x", y="y", data=death_by_build, bins=9, cbar=True, cmap="Reds");
ax.scatter(death_by_build.x, death_by_build.y, color='r', s=20, ec='k');
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn [10], line 4[0m
[0;32m      1[0m [38;5;66;03m# Generate scatter plot[39;00m
[0;32m      2[0m f, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m----> 4[0m sns[38;5;241m.[39mhistplot(x[38;5;241m=[39m[38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m, y[38;5;241m=[39m[38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m, data[38;5;241m=[39mdeath_by_build, bins[38;5;241m=[39m[38;5;241m9[39m, cbar[38;5;241m=[39m[38;5;28;01mTrue[39;00m, cmap[38;5;241m=[39m[38;5;124m"[39m[38;5;124mReds[39m[38;5;124m"[39m);
[0;32m      5[0m ax[38;5;241m.[39mscatter(death_by_build[38;5;241m.[39mx, death_by_build[38;5;241m.[39my, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, s[38;5;241m=[39m[38;5;241m20[39m, ec[38;5;241m=[39m[38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m)

[1;31mAttributeError[0m: module 'seaborn' has no attribute 'histplot'
AttributeError: module 'seaborn' has no attribute 'histplot'

